// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMember = `-- name: CreateMember :one
INSERT INTO library.member (
    username,
    first_name,
    last_name,
    gender,
    date_of_birth,
    member_since,
    is_student,
    email_address,
    interests
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING
    id,
    version,
    username,
    first_name,
    last_name,
    gender,
    date_of_birth,
    member_since,
    is_student,
    email_address,
    interests,
    generated,
    updated
`

type CreateMemberParams struct {
	Username     string            `json:"username"`
	FirstName    string            `json:"first_name"`
	LastName     string            `json:"last_name"`
	Gender       NullLibraryGender `json:"gender"`
	DateOfBirth  pgtype.Date       `json:"date_of_birth"`
	MemberSince  pgtype.Date       `json:"member_since"`
	IsStudent    pgtype.Bool       `json:"is_student"`
	EmailAddress string            `json:"email_address"`
	Interests    []byte            `json:"interests"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (LibraryMember, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
		arg.DateOfBirth,
		arg.MemberSince,
		arg.IsStudent,
		arg.EmailAddress,
		arg.Interests,
	)
	var i LibraryMember
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.DateOfBirth,
		&i.MemberSince,
		&i.IsStudent,
		&i.EmailAddress,
		&i.Interests,
		&i.Generated,
		&i.Updated,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :execrows
DELETE FROM library.member
WHERE id = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMember, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT
    id,
    version,
    username,
    first_name,
    last_name,
    gender,
    date_of_birth,
    member_since,
    is_student,
    email_address,
    interests,
    generated,
    updated
FROM library.member
WHERE id = $1
`

func (q *Queries) GetMemberByID(ctx context.Context, id int32) (LibraryMember, error) {
	row := q.db.QueryRow(ctx, getMemberByID, id)
	var i LibraryMember
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.DateOfBirth,
		&i.MemberSince,
		&i.IsStudent,
		&i.EmailAddress,
		&i.Interests,
		&i.Generated,
		&i.Updated,
	)
	return i, err
}

const searchMembers = `-- name: SearchMembers :many
SELECT
    id,
    version,
    username,
    first_name,
    last_name,
    gender,
    date_of_birth,
    member_since,
    is_student,
    email_address,
    interests,
    generated,
    updated
FROM library.member
WHERE
    ($1::text IS NULL OR username ILIKE '%' || $1::text || '%')
    AND ($2::text IS NULL OR email_address ILIKE '%' || $2::text || '%')
    AND ($3::text IS NULL OR last_name ILIKE '%' || $3::text || '%')
ORDER BY id
LIMIT $5
OFFSET $4
`

type SearchMembersParams struct {
	Username     pgtype.Text `json:"username"`
	EmailAddress pgtype.Text `json:"email_address"`
	LastName     pgtype.Text `json:"last_name"`
	Offset       int32       `json:"offset"`
	Limit        int32       `json:"limit"`
}

func (q *Queries) SearchMembers(ctx context.Context, arg SearchMembersParams) ([]LibraryMember, error) {
	rows, err := q.db.Query(ctx, searchMembers,
		arg.Username,
		arg.EmailAddress,
		arg.LastName,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LibraryMember
	for rows.Next() {
		var i LibraryMember
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Gender,
			&i.DateOfBirth,
			&i.MemberSince,
			&i.IsStudent,
			&i.EmailAddress,
			&i.Interests,
			&i.Generated,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMember = `-- name: UpdateMember :one
UPDATE library.member
SET
    version = version + 1,
    username = $3,
    first_name = $4,
    last_name = $5,
    gender = $6,
    date_of_birth = $7,
    member_since = $8,
    is_student = $9,
    email_address = $10,
    interests = $11,
    updated = now()
WHERE id = $1
  AND version = $2
RETURNING
    id,
    version,
    username,
    first_name,
    last_name,
    gender,
    date_of_birth,
    member_since,
    is_student,
    email_address,
    interests,
    generated,
    updated
`

type UpdateMemberParams struct {
	ID           int32             `json:"id"`
	Version      int32             `json:"version"`
	Username     string            `json:"username"`
	FirstName    string            `json:"first_name"`
	LastName     string            `json:"last_name"`
	Gender       NullLibraryGender `json:"gender"`
	DateOfBirth  pgtype.Date       `json:"date_of_birth"`
	MemberSince  pgtype.Date       `json:"member_since"`
	IsStudent    pgtype.Bool       `json:"is_student"`
	EmailAddress string            `json:"email_address"`
	Interests    []byte            `json:"interests"`
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (LibraryMember, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.ID,
		arg.Version,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
		arg.DateOfBirth,
		arg.MemberSince,
		arg.IsStudent,
		arg.EmailAddress,
		arg.Interests,
	)
	var i LibraryMember
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.DateOfBirth,
		&i.MemberSince,
		&i.IsStudent,
		&i.EmailAddress,
		&i.Interests,
		&i.Generated,
		&i.Updated,
	)
	return i, err
}
