// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type LibraryGender string

const (
	LibraryGenderMALE    LibraryGender = "MALE"
	LibraryGenderFEMALE  LibraryGender = "FEMALE"
	LibraryGenderDIVERSE LibraryGender = "DIVERSE"
)

func (e *LibraryGender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LibraryGender(s)
	case string:
		*e = LibraryGender(s)
	default:
		return fmt.Errorf("unsupported scan type for LibraryGender: %T", src)
	}
	return nil
}

type NullLibraryGender struct {
	LibraryGender LibraryGender `json:"library_gender"`
	Valid         bool          `json:"valid"` // Valid is true if LibraryGender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLibraryGender) Scan(value interface{}) error {
	if value == nil {
		ns.LibraryGender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LibraryGender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLibraryGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LibraryGender), nil
}

type LibraryMember struct {
	ID           int32              `json:"id"`
	Version      int32              `json:"version"`
	Username     string             `json:"username"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	Gender       NullLibraryGender  `json:"gender"`
	DateOfBirth  pgtype.Date        `json:"date_of_birth"`
	MemberSince  pgtype.Date        `json:"member_since"`
	IsStudent    pgtype.Bool        `json:"is_student"`
	EmailAddress string             `json:"email_address"`
	Interests    []byte             `json:"interests"`
	Generated    pgtype.Timestamptz `json:"generated"`
	Updated      pgtype.Timestamptz `json:"updated"`
}
