name: Analyze code

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
